### ISSUE TITLE
""o" already used" in miles_with_expiration_simple.arl

### ISSUE THREAD

**Issue by rognierbenoit** [edukera/archetype-lang#128]
<img width="715" alt="Screenshot 2019-11-07 at 18 12 41" src="https://user-images.githubusercontent.com/4006868/68411375-aa26b700-018a-11ea-8709-5bbcf862cbf0.png">

```
benoitrognier@mbp:~/Documents/archetype-lang$ ./archetype.exe ./contracts/miles_with_expiration_simple.arl 
File "./contracts/miles_with_expiration_simple.arl", line 41, characters 980-981: Name is already used: "o"

./contracts/miles_with_expiration_simple.arl: line 41 (24-25): Name is already used: "o"
```

**Comment by strub** [comment]
The name clash is genuine. I made a better error reporting:

`contracts/miles_with_expiration_simple.arl: line 41 (24-25): Name is already bound: "o" (previous definition: contracts/miles_with_expiration_simple.arl: line 56 (9-10))`

**Comment by strub** [comment]
Note that, due to the design of archetype, the typing is not linear. Hence, the declaration at line 56 is indeed the first one.
