### ISSUE TITLE
Rule spec_effect in parser seems unreachable

### ISSUE THREAD

**Issue by strub** [edukera/archetype-lang#134]

**Comment by guillaumeduhamel** [comment]
In this example: [tests/test_specification.arl](https://github.com/edukera/archetype-lang/blob/dev/tests/test_specification.arl)
now, there is an effect in a specification section, which works (the parse tree seems to be correct).
The effect must be before postconditions.
```
spec_items:
| ds=loc(spec_definition)*
  ps=loc(spec_predicate)*
  xs=loc(spec_lemma)*
  ts=loc(spec_theorem)*
  vs=loc(spec_variable)*
  es=loc(spec_effect)*
  bs=loc(spec_assert)*
  ss=loc(spec_postcondition)*
   { ds @ ps @ xs @ ts @ vs @ es @ bs @ ss }
```
there aren't pipe before `id=loc(spec_section)` (expect the first), so this order must be respected
We do that to normalize specification sections between contracts.
Tell me if it's okay for you

**Comment by strub** [comment]
What's the meaning of having effects in specifications?

**Comment by guillaumeduhamel** [comment]
it's for ghost variable updating,
here is an example: [onlyonce.arlx](https://github.com/edukera/archetype-lang/blob/dev/extensions/onlyonce.arlx)

**Comment by guillaumeduhamel** [comment]
only ghost variables can be updated here,
the typer should reject storage (or transfer) side effect
