### ISSUE TITLE
contracts

### ISSUE THREAD

**Issue by guillaumeduhamel** [edukera/archetype-lang#135]
all contracts :
- [ ] animal_tracking
- [ ] auction
- [ ] auction_lazy
- [ ] auction_no_memory
- [ ] auction_zilliqa
- [ ] autocallable
- [ ] bond
- [ ] c3n
- [ ] c3n_without_loop
- [x] certificate_generator
- [ ] clause_io_acceptance_of_delivery
- [ ] coase
- [ ] competition
- [x] empty
- [ ] erc20
- [ ] erc721
- [ ] escrow_basic
- [x] escrow_penalty
- [ ] escrow_simple
- [x] escrow_without_spec
- [ ] fizzy
- [ ] guarantee_fund
- [ ] health_care
- [x] hello
- [ ] ico
- [ ] miles
- [x] miles_with_expiration
- [ ] miles_with_expiration_simple
- [ ] mini_dao
- [x] mwe_medium
- [ ] perishable
- [ ] vehicle_lifecycle
- [ ] voting_process
- [ ] zero_coupon_bond
- [x] zero_coupon_bond_with_insurance

tasks:
- [x] arithmetic operations
[passed/lang_arith.arl](../blob/dev/tests/passed/lang_arith.arl)
- [x] handle builtin functions (`min` and `max`)
[passed/lang_funs.arl](../blob/dev/tests/passed/lang_funs.arl)
- [x] cannot update key in asset
[type-errors/no_update_asset_key.arl](../blob/dev/tests/type-errors/no_update_asset_key.arl)
- [ ] no postcondition in global spec
[type-errors/no_postcondition_in_global_spec.arl](../blob/dev/tests/type-errors/no_postcondition_in_global_spec.arl)
- [ ] no contract invariant in function spec
[type-errors/no_contract_invariant_in_fun_spec.arl](../blob/dev/tests/type-errors/no_contract_invariant_in_fun_spec.arl)
- [ ] handle function
[passed/fun.arl](../blob/dev/tests/passed/fun.arl)
- [ ] handle `result` constant in formula
[passed/test_result.arl](../blob/dev/tests/passed/test_result.arl)
- [ ] reject `result` in prog
[type-errors/no_result_in_prog.arl](../blob/dev/tests/type-errors/no_result_in_prog.arl)
- [x] map fail instruction in `Ifail`
[passed/effect_fail.arl](../blob/dev/tests/passed/effect_fail.arl)
- [x] map `Enothing` in pt to `Iseq []` in ast
[passed/nothing.arl](../blob/dev/tests/passed/nothing.arl)
- [ ] asset field cannot be typed by another asset
[type-errors/no_asset_in_asset.arl](../blob/dev/tests/type-errors/no_asset_in_asset.arl)
- [x] handle assignment
[passed/assign.arl](../blob/dev/tests/passed/assign.arl)
- [x] handle `any` and `or` operation in `from` expression in transition
[passed/test_transition.arl](../blob/dev/tests/passed/test_transition.arl)
- [x] handle option literals (`none` and `some(0)`)
[passed/lang_literals.arl](../blob/dev/tests/passed/lang_literals.arl)
- [ ] replace a collection of asset with literals
[passed/assign_asset_collection.arl](../blob/dev/tests/passed/assign_asset_collection.arl)
- [x] reject same name functions/actions
[type-errors/duplicated_action.arl](../blob/dev/tests/type-errors/duplicated_action.arl)
- [x] asset field does not be considered like method call and must be rejected
[type-errors/field_method.arl](../blob/dev/tests/type-errors/field_method.arl)
- [x] allow comparison with eq and ne cmp operators between int and rational operands
[passed/expr_cmp_eq_int_rat.arl](../blob/dev/tests/passed/expr_cmp_eq_int_rat.arl)
[passed/expr_cmp_ne_int_rat.arl](../blob/dev/tests/passed/expr_cmp_ne_int_rat.arl)
[passed/expr_cmp_eq_rat_int.arl](../blob/dev/tests/passed/expr_cmp_eq_rat_int.arl)
[passed/expr_cmp_ne_rat_int.arl](../blob/dev/tests/passed/expr_cmp_ne_rat_int.arl)
- [x] update the type of assigned entity in `Iassign` constructor (line 2298)
- [x] Fill initial value of asset (line 3305)
[passed/lang_asset.arl](../blob/dev/tests/passed/lang_asset.arl)
- [x] Handle divrat operator (operands must be typed int, reject all other situation)
[passed/expr_lit_rat_div.arl](../blob/dev/tests/passed/expr_lit_rat_div.arl)
- [ ] Bind global variable in shadow effect
[passed/shadow_global_var_effect.arl](../blob/dev/tests/passed/shadow_global_var_effect.arl)
[type-errors/no_assignment_of_prog_var_in_shadow_effect.arl](../blob/dev/tests/type-errors/no_assignment_of_prog_var_in_shadow_effect.arl)
[type-errors/no_assignment_of_shadow_var_in_prog_effect.arl](../blob/dev/tests/type-errors/no_assignment_of_shadow_var_in_prog_effect.arl)
- [x] Handle `abs` function (`Cabs` is added in ast)
[passed/expr_fun_abs_int.arl](../blob/dev/tests/passed/expr_fun_abs_int.arl)
[passed/expr_fun_abs_rat.arl](../blob/dev/tests/passed/expr_fun_abs_rat.arl)
- [x] Handle `list` type
[passed/lang_list.arl](../blob/dev/tests/passed/lang_list.arl)
[passed/effect_method_list_prepend.arl](../blob/dev/tests/passed/effect_method_list_prepend.arl)
[passed/expr_method_list_contains.arl](../blob/dev/tests/passed/expr_method_list_contains.arl)
[passed/expr_method_list_count.arl](../blob/dev/tests/passed/expr_method_list_count.arl)
[passed/expr_method_list_nth.arl](../blob/dev/tests/passed/expr_method_list_nth.arl)
- [x] Fill enum in ast
[passed/lang_enum.arl](../blob/dev/tests/passed/lang_enum.arl)
- [x] Fill `on` field in transition
[passed/contract_transition_on_asset.arl](../blob/dev/tests/passed/contract_transition_on_asset.arl)
- [x] Reject assignment of iter loop variable
[type-errors/no_assignment_var_iter.arl](../blob/dev/tests/type-errors/no_assignment_var_iter.arl)
- [x] Reject local variable in sum expression
[type-errors/no_var_sum.arl](../blob/dev/tests/type-errors/no_var_sum.arl)
- [x] Accept sort with several criteria
[passed/multi_sort.arl](../blob/dev/tests/passed/multi_sort.arl)
- [ ] `decls` and `funs` in ast model type must be in the right order
- [ ] Handle `pkey of asset` type in asset field when asset is declared after current asset
[contracts/animal_tracking.arl](../blob/dev/contracts/animal_tracking.arl)
- [ ] Fill shadow value in asset item (asset_struct:fields -> decl_gen:shadow)
[passed/shadow_field.arl](../blob/dev/tests/passed/shadow_field.arl)
- [ ] Reject variable declared in effect block in formula
[type-errors/no_effect_local_var_in_formula.arl](../blob/dev/tests/type-errors/no_effect_local_var_in_formula.arl)
- [x] Handle entry calling of remote contract
[type-errors/bad_contract_calling_arg.arl](../blob/dev/tests/type-errors/bad_contract_calling_arg.arl)
[type-errors/bad_contract_calling_id.arl](../blob/dev/tests/type-errors/bad_contract_calling_id.arl)
[type-errors/bad_contract_calling.arl](../blob/dev/tests/type-errors/bad_contract_calling.arl)
[passed/test_contract.arl](../blob/dev/tests/passed/test_contract.arl)
- [ ] Handle vset (added; removed; unmoved) (../blob/dev/tests/passed/lang_formula_asset_api.arl)
- [ ] Handle mutually recursive asset (../blob/dev/contracts/animal_tracking.arl)
- [ ] Add cast from collection to view 
[passed/implicit_cast_to_view.arl](../blob/dev/tests/passed/implicit_cast_to_view.arl)
[passed/asset_collect_to_view.arl](../blob/dev/tests/passed/asset_collect_to_view.arl)
- [x] Reject asset effect with view
[type-errors/no_asset_effect_on_view_add.arl](../blob/dev/tests/type-errors/no_asset_effect_on_view_add.arl)
[type-errors/no_asset_effect_on_view_addupdate.arl](../blob/dev/tests/type-errors/no_asset_effect_on_view_addupdate.arl)
[type-errors/no_asset_effect_on_view_clear.arl](../blob/dev/tests/type-errors/no_asset_effect_on_view_clear.arl)
[type-errors/no_asset_effect_on_view_remove.arl](../blob/dev/tests/type-errors/no_asset_effect_on_view_remove.arl)
[type-errors/no_asset_effect_on_view_add.arl](../blob/dev/tests/type-errors/no_asset_effect_on_view_add.arl)
[type-errors/no_asset_effect_on_view_update.arl](../blob/dev/tests/type-errors/no_asset_effect_on_view_update.arl)
- [x] Reject pkey assignment on update and addupdate
[type-errors/no_pkey_assignment_in_update.arl](../blob/dev/tests/type-errors/no_pkey_assignment_in_update.arl)
[type-errors/no_pkey_assignment_in_addupdate.arl](../blob/dev/tests/type-errors/no_pkey_assignment_in_addupdate.arl)
- [x] Fill `Rexpr` on calledby transaction
- [x] Remove formula behavior on `require` and `failif` instruction
[passed/method_in_require_or_failif.arl](../blob/dev/tests/passed/method_in_require_or_failif.arl)
- [x] Update select typing
[passed/select_with_extra_var.arl](../blob/dev/tests/passed/select_with_extra_var.arl)
[passed/operator_in_select.arl](../blob/dev/tests/passed/operator_in_select.arl)
[type-errors/no_method_in_select.arl](../blob/dev/tests/type-errors/no_method_in_select.arl)
- [x] Fill `AFun`
- [x] Do not ignore asset with labeled record in initialization
[passed/test_init_asset2.arl](../blob/dev/tests/passed/test_init_asset2.arl)
- [x] Support `+=` and `-=` operators for collection and partition in update effect
[passed/effect_method_asset_update_with_add_collection_field.arl](../blob/dev/tests/passed/effect_method_asset_update_with_add_collection_field.arl)
[passed/effect_method_asset_update_with_remove_collection_field.arl](../blob/dev/tests/passed/effect_method_asset_update_with_remove_collection_field.arl)
- [ ] Reject duplicate keys in init asset
[type-errors/duplicated_keys_in_init_asset.arl](../blob/dev/tests/type-errors/duplicated_keys_in_init_asset.arl)

**Comment by strub** [comment]
The field `effect` of `Ast.specification` should be an instruction, not a expression.

**Comment by strub** [comment]
It is unclear in which context the variables invariants should be typed. Does a variable invariant can refer to some other variables. In the former case, could we have mutually recursive invariants (w.r.t their respective variables)?
