### ISSUE TITLE
why3 prove ... Library file not found: archetype

### ISSUE THREAD

**Issue by ang-st** [edukera/archetype-lang#148]
Hi, 
I try to launch `why3` prover against generated `mlw`.
why3 complains as he doesn't find archtype library

```
why3 prove erc20.mlw                 
File "erc20.mlw", line 2, characters 2-19:
Library file not found: archetype
```
I guess it is related to passing the right `--library` value. 

Can you point me in the right direction ?

**Comment by rognierbenoit** [comment]
Hi,
the `archetype.mlw` lib is in the `mlw/` directory of archetype, hence you should use the why3 `-L` option to point to this dir; for example assuming you run the command from the archetype dir, it should be something like
```why3 prove -L ./mlw erc20.mlw```

**Comment by ang-st** [comment]
Thanks !
as it might help someone,  using opam installation, `mlw` directory is located at  `$HOME/.opam/ocaml_version/share/archetype/mlw/`
