### ISSUE TITLE
WHY3 : archetype.mlw   Symbol string is already defined in the current scope

### ISSUE THREAD

**Issue by ang-st** [edukera/archetype-lang#149]
Hi again, 
while trying to run `prove`, why3 fail with following error

```
$ why3 prove erc20.mlw -L /home/ang-st/.opam/4.10.0/share/archetype/mlw  
File "/home/ang-st/.opam/4.10.0/share/archetype/mlw/archetype.mlw", line 11, characters 2-20:
Symbol string is already defined in the current scope
```
Am i missing something  ?

**Comment by rognierbenoit** [comment]
no, the last versions of why3 (1.3.x) now define a native string type which conflicts with the archetype one. The coming release 0.1.14 of archetype is fixing that;  it is in the opam release pipe and should be available very soon ...

https://github.com/ocaml/opam-repository/pull/16286

so for right now you can either 
* go back to why3 1.2.x  
* wait for this coming release
* or build archetype from master branch (you need to create an opam switch first with at least OCAML_VERSION>=4.07.0, and then run `make build-deps all install` once in the switch)

Sorry for the inconvenience.
