### ISSUE TITLE
archetype.0.1.14,  Error (parsing) on erc20 example

### ISSUE THREAD

**Issue by ang-st** [edukera/archetype-lang#150]
Hi, 
I did not deeply investigate changelog but example[ erc20 ](https://docs.archetype-lang.org/contract-library/tokens/erc20 ) doesn't transpile anymore on  0.1.14

0.1.13
```
$ archetype  -t whyml erc20.arl > /dev/null; echo $? 
0
```
0.1.14
```
$ archetype  -t whyml erc20.arl
File "erc20.arl", line 24, characters 17-18: Error (parsing)
  Error while analyzing asset post option.%   
```

**Comment by rognierbenoit** [comment]
Hi, if you take the erc20 which comes with the 0.1.14 it should work
`archetype -t whyml ${OPAM_SWITCH_PREFIX}/share/archetype/contracts/erc20.arl`

**Comment by ang-st** [comment]
Hi,
worked, thanks for pointing this out :)
