### ISSUE TITLE
Why3 error while using "asset with" and "partition in asset"

### ISSUE THREAD

**Issue by dakk** [edukera/archetype-lang#152]
Archetype version 0.1.14

Writing few test contract, I'm encountering two unexpected behaviours; I wrote two mini contracts to reproduce the problem. 

The first arises when I compare float in an asset definition:

```
archetype langtest

asset u identified by addr {
	addr	: address;
	mg		: rational;
} with {
	u1		: mg < 10.0 and mg > 0.0;
}

action start () { effect { () } }
```

running why3 prover, it produces:
```
why3 -L ~/.opam/default/share/archetype/mlw/ prove out/lang_test_fcmp.mlw
[useless warnings]
File "out/lang_test_fcmp.mlw", line 59, characters 6-10:
This term has type (int, int), but is expected to have type int
make: *** [Makefile:30: prove] Error 1
```

The second arises when I try to use a partition inside an asset:
```
archetype langtest

asset et identified by cid { cid: int; }

asset e identified by eid {
	eid			: string;
	cells		: et partition;
}

action start (cl: et partition) {
	effect {
		var ev : e = { eid = "123"; cells = cl };
	}
}
```
running why3 prover, it produces:

```
why3 -L ~/.opam/default/share/archetype/mlw/ prove out/lang_test_part.mlw
[useless warnings]
File "out/lang_test_part.mlw", line 118, characters 15-17:
This expression has type Langtest_storage.Et.collection,
but is expected to have type list.List.list int
make: *** [Makefile:30: prove] Error 1
```

**Comment by rognierbenoit** [comment]
Hi Dakk,
thank you for the report. 
* the first issue is fixed and will be available in the main branch soon (couple of weeks).
* the second point is not meant to be possible: in the next release, it won't be possible to pass partition as action argument. The solution will be to pass a list of assets and add each of them to the partition. 

Note that Archetype has not yet reached release (v1) but we are working on it!

**Comment by dakk** [comment]
I just saw the fix in the dev branch (y) I know archetype is still in early stage, and I'm not expecting a readytouse compiler; btw I'm following the development since I want to use it when will be stable, and also I want to learn more about how compiler works. I'll open issues only if I'm sure there is one (like the first part of this one); I try not to be too harassing :)
