### ISSUE TITLE
seems like transfer is not an allowed name for an entry

### ISSUE THREAD

**Issue by chiptus** [edukera/archetype-lang#198]
As a test for archetype, I'm trying to implement a FA1.2 token using archetype.

One of the entry points needs to be "transfer", but the compiler fails with it. The error I get is " Error while analyzing an entry or an entry", but the name is marked by the error.

**Comment by rognierbenoit** [comment]
Hi Chiptus, a FA12 implementation is available in the dev branch. It will be merged and released as 1.1 by the end of this week!
https://github.com/edukera/archetype-lang/blob/dev/contracts/fa12.arl
https://docs.archetype-lang.org/v/v1.1/contract-library/tokens/fa-1.2

In 1.1, it will be possible to use `%transfer` as entrypoint name when conflicting with a language keyword.

**Comment by chiptus** [comment]
thanks for the fast replies! 
is there anything else I should be aware of? I still want to implement by myself to learn :)

**Comment by rognierbenoit** [comment]
the 1.1 version fixes many things and the language is now stable.
so maybe the best thing is to wait for this version (end of week).

the verification part is under active dev. and should be fully operational by September.

In the meantime, you may have a look at the contract library (~20 of them in the `~/.opam/%YOUR_SWITCH%/share/archetype/contracts` dir).

**Comment by chiptus** [comment]
great, thanks.

looking forward to it
