### ISSUE TITLE
Unbound symbol `string`

### ISSUE THREAD

**Issue by Coda-Coda** [edukera/archetype-lang#201]
I get the following error on running `>Archetype: Verify with Why3` in VSCode.
Any suggestions?
`...archetype.mlw", line 6, characters 19-25: 
unbound symbol 'string'`

**Comment by rognierbenoit** [comment]
Hi Coda,

`string` is  a built-in why3 type : http://why3.lri.fr/stdlib/string.html

It's been so for several versions of why3. What is the result of 
```
why3 --version
```
when typed in the VS Code terminal ?

**Comment by Coda-Coda** [comment]
$ why3 --version
Why3 platform, version 1.2.1

**Comment by rognierbenoit** [comment]
ok, you should use at least version 1.3.2.

**Comment by Coda-Coda** [comment]
Ok, I will try that, thanks.

**Comment by Coda-Coda** [comment]
@rognierbenoit I'm trying to use NixOS you see, do you happen to have any tips on getting why3 1.3.2 working on NixOS? (preferably without opam).
I managed to get archetype working without opam on NixOS [here](https://github.com/Coda-Coda/archetype-lang/blob/master/README-Nix.md) if you are interested. (Note that I'm new to NixOS so there may be other better ways).

**Comment by Coda-Coda** [comment]
1.3.2 works. [This](https://github.com/yrashk/nixpkgs/tree/why3-1.3.2/pkgs/applications/science/logic/why3) was useful.
