### ISSUE TITLE
Strange compilation parser error

### ISSUE THREAD

**Issue by bobobobob** [edukera/archetype-lang#214]
Example code from official documentation dosen't compile:
```
archetype inspector

variable foo : int = 0

entry setFoo(v : int) { foo := v }

entry getFoo(asender : address) { 
  transfer 0tz to asender call getBar<entrysig<int>>(self.setFoo) 
}
```
it gives following error:
File "inspector.arl", line 8, characters 46-47: Error (parsing)

This kind of error persists whenever there are nested <> in transfer

**Comment by guillaumeduhamel** [comment]
thank you for your report, there is a mistake in the documentation

`entrysig` must be replaced by `contract`

here is the right version of your example :

```
archetype inspector

variable foo : int = 0

entry setFoo(v : int) { foo := v }

entry getFoo(asender : address) { 
  transfer 0tz to asender call getBar<contract<int>>(self.setFoo) 
}
```

**Comment by bobobobob** [comment]
Wow! Thank you for quick reply! 
There is also a small mistake in mentioned example - it says '0tez' instead of 0tz...

**Comment by guillaumeduhamel** [comment]
ok the documentation is fixed, `entrysig` was used in previous version instead of `contract` now (like `michelson` type).
Thank you again for the reporting !
