### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by matthewdowns** [edukera/archetype-lang#217]
### Request
It would be wonderful if Archetype could read either from a .env file or the operating system's exported environment variables.

### Reasoning
Environment variables would make it much easier to store contract code on GitHub with other team members, since typically contracts will have an _owner_ variable, which changes based on the developer deploying the contract. It's also useful for setting variables to be different based on if it's going to the testnet or mainnet.

### Collaboration
I am available to assist in adding in this feature if more bandwidth is required to complete this task - please let me know.

Thank you!

**Comment by rognierbenoit** [comment]
Hello Matthew, thank you for your request.

It seems to me there are ways to get what you need, and I want first to check that with you.

Archetype has the possibility to declare contract parameters: typically the `owner` of a contract can be a parameter as in the following example:

```
archetype example(owner : address)

entry default() {
   transfer (2% * transferred) to owner
}
```

You then pass the value of the parameter at origination; with [completium-cli](https://completium.com/docs/cli) you would do:

```
$ completium-cli deploy example.arl --with $OWNER
```

To read a .env from a file, you can use for example the `eval` command to load it in the current environment:

```
$ cat test.env
 OWNER='@tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb'
$ eval $(cat test.env)
$ completium-cli deploy example.arl --with $OWNER
```

Please let me know if it answers your request.

**Comment by matthewdowns** [comment]
Unfortunately that did not work fo me, I'm getting a parsing error in VS Code when adding in the parentheticals on the archetype line:

<img width="470" alt="Screen Shot 2021-04-25 at 10 50 47 AM" src="https://user-images.githubusercontent.com/49664210/116000021-221db280-a5b4-11eb-83b7-027c872a1c2a.png">

**Comment by rognierbenoit** [comment]
Hello Matthews, it is a version issue.
The last version of Archetype is 1.2.3. Check version with:
```
archetype --version
```
If you installed it with opam, you can update to last version with:
```
opam update
opam install archetype.1.2.3
```
or you can download it from `https://github.com/edukera/archetype-lang/releases` for Linux or Macos.

**Comment by matthewdowns** [comment]
> Hello Matthews, it is a version issue.
> The last version of Archetype is 1.2.3. Check version with:
> 
> ```
> archetype --version
> ```
> 
> If you installed it with opam, you can update to last version with:
> 
> ```
> opam update
> opam install archetype.1.2.3
> ```
> 
> or you can download it from `https://github.com/edukera/archetype-lang/releases` for Linux or Macos.

Thank you Benoit! That worked updating the version to 1.2.3.

**Comment by matthewdowns** [comment]
Closing since this issue was resolved.
