### ISSUE TITLE
Provide example of how to write a FA2 contract in Archetype docs

### ISSUE THREAD

**Issue by matthewdowns** [edukera/archetype-lang#218]
<img width="304" alt="Screen Shot 2021-04-25 at 1 42 32 PM" src="https://user-images.githubusercontent.com/49664210/116005371-39689a00-a5cc-11eb-9f60-1f3b13bd78e3.png">

**Comment by rognierbenoit** [comment]
Here is the link to the archetype FA 2

https://completium.com/docs/templates/nft

Do not hesitate if questions.

**Comment by matthewdowns** [comment]
> Here is the link to the archetype FA 2
> 
> https://completium.com/docs/templates/nft
> 
> Do not hesitate if questions.

Thank you again Benoit, you've been a great help. I'm getting an error now when trying to be compliant to TZIP-016 standards requiring an asset named **metadata**, I get this:
<img width="577" alt="Screen Shot 2021-04-25 at 4 55 35 PM" src="https://user-images.githubusercontent.com/49664210/116010824-10a1ce00-a5e7-11eb-8477-8f3baed25d1f.png">

TZIP-012 specification allows for a **token_metadata** (which compiles successfully), but I want to be compliant with TZIP-016, which is what Temple Wallet is looking for when adding a non-fungible token to your wallet:
<img width="618" alt="Screen Shot 2021-04-25 at 4 56 48 PM" src="https://user-images.githubusercontent.com/49664210/116010862-3fb83f80-a5e7-11eb-924d-bcbffce06caa.png">

Would you know why the Archetype linter is saying **metadata** has a previous definition even though there is none?

**Comment by guillaumeduhamel** [comment]
Hi Matthew,

Here is the link to tzip-16 specification with archetype:
https://docs.archetype-lang.org/archetype-language/metadata-tzip-16

For the linter, in archetype, `metadata` identifier is reserved for a variable typed `big_map<string, bytes>`, so you cannot use this identifier to name an asset.

Let me know if you have any other questions or comments,
