### ISSUE TITLE
Tutorial is broken

### ISSUE THREAD

**Issue by FreedomPrevails** [edukera/archetype-lang#238]
Hi,
I tried your tutorial on gitpod and here is the code that I used :

```
archetype hello

variable value : string = ""

entry main () {
  value := "Hello Tezos world!"
}
```
but after deploying it, completium-cli cant call the main with following error :
> $ completium-cli call 1-hello
> main is not found.

is the tutorial up to date and supposed to work ?

**Comment by rognierbenoit** [comment]
Hi @FreedomPrevails thanks for the report, it is fixed now. 
Indeed we recently changed the way `completium-cli` calls contracts with only one entry point; now there is no special treatment and you need to specify the entry point anyway; hence here the command is:
```
$ completium-cli call 1-hello --entry main
```

Kind regards.

**Comment by FreedomPrevails** [comment]
Thank you for your reply.
Sorry to bother you but now I have a problem with part 2 of tutorial.
Based on the code, it should not accept any odd numbers and should fail but I was able to set it to 15 ! is this a bug ?
Here is the contract :
https://better-call.dev/granadanet/KT1LsLmriSynuLuvkBEu5TNyHDAYdj44v8MB/operations

**Comment by FreedomPrevails** [comment]
I found the problem. seems the code in tutorial is wrong, r2 has used value instead of v :
`r2 otherwise "EXPECTED EVEN VALUE": value % 2 = 0`
it should be :
`r2 otherwise "EXPECTED EVEN VALUE": v % 2 = 0`

**Comment by FreedomPrevails** [comment]
I am starting to learn tezos smart contract programming, there are a few other choices like ligo and smartpy and etc.
do you think archetype is stable and production ready ? does it provide all the required features for smart contract programming right now ?

**Comment by rognierbenoit** [comment]
Hi @FreedomPrevails ,
Thank you for your feedback, 
indeed the value should be `v` and not `value`... it is fixed now.

Yes Archetype is stable and active; it produces production quality code and provides the required features:
* all Michelson primitives are available
* high-level abstractions to ease contract programming (new types, state machine, assets ...)
* VS code extension with syntax highlighting and compilation commands
* formal specification language for formal verification with [why3](http://why3.lri.fr/)
* dedicated [JS lib](https://completium.com/docs/cli/jslibrary) for test scenarios

We are currently working on a decompiler Michelson --> Archetype, and step by step execution in VS code.

Hope this helps,
Benoit
