### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by guillaumeduhamel** [edukera/archetype-lang#319]
RENAME

section

- [x] refuse transfer -> no transfer
- [x] failif -> fail if

instruction

- [x] dorequire -> do_require
- [x] dofailif -> do_fail_if

constant

- [x] chainid -> self_chain_id
- [x] selfaddress -> self_address

builtin

- [x] callview -> call_view
- [x] contract_address -> contract_to_address
- [x] date_from_timestamp -> int_to_date
- [x] getopt -> get
- [x] hash_key -> key_to_key_hash
- [x] implicit_account -> key_hash_to_contract
- [x] isnat -> int_to_nat
- [x] isnone -> is_none
- [x] issome -> is_some
- [x] key_address -> key_to_address
- [x] mkoperation -> make_operation
- [x] opt_get -> get_some
- [x] require_some -> get_some with 2 arguments
- [x] to_string -> nat_to_string
- [x] entrypoint -> get_entrypoint

asset

- [x] getopt -> get
- [x] addupdate -> add_update
- [x] removeif -> remove_if
- [x] clear -> remove_all (except view)

fail

- [x] InvalidCaller -> INVALID_CALLER
- [x] InvalidSource -> INVALID_SOURCE
- [x] InvalidCondition -> INVALID_CONDITION
- [x] NotFound -> NOT_FOUND
- [x] AssetNotFound -> ASSET_NOT_FOUND
- [x] KeyExists -> KEY_EXISTS
- [x] KeyExistsOrNotFound -> KEY_EXISTS_OR_NOT_FOUND
- [x] OutOfBound -> OUT_OF_BOUND
- [x] divbyzero -> DIV_BY_ZERO
- [x] NegResult -> NAT_NEG_ASSIGN
- [x] NatAssign -> NAT_NEG_ASSIGN
- [x] NoTransfer -> NO_TRANSFER
- [x] InvalidState -> INVALID_STATE

REMOVE

- [x] to_nat
- [x] require_entrypoint

**Comment by rognierbenoit** [comment]
```
implicit_account -> key_hash_to_contract
```
