### ISSUE TITLE
VSCode Extension

### ISSUE THREAD

**Issue by nicosampler** [edukera/archetype-lang#78]
Hi I'm trying to install the extension for vscode with no luck.
If I try through the vscode search bar it does not appears. If I try using the command it says "No Extension found".

Any Idea what can be wrong?

**Comment by rognierbenoit** [comment]
Hi Nico,
the extension is not yet released ! should by next month.

**Comment by nicosampler** [comment]
are you using another tool meanwhile? I need to create a few contracts and I've chosen archetype to do it.

**Comment by rognierbenoit** [comment]
Nice to hear! 

Archetype language is still under (active) development though,
it is too early to consider it for deployment.

What we could do however is to transcode your contracts to Archetype as a test; it will help us improve it; we could even give a hand to verify them with the wyml generation.

**Comment by nicosampler** [comment]
Thx so much! The contracts won't be deployed in mainnet, they will be for educative purposes for Tezos, and will be deployed in alphanet, Also they won't be so different as the one you have in the example sections of your documentation. I have to deliver those contracts in 1.5 months, do you think I have to choose another language like Ligo? Or the current status is ok for my goal?

**Comment by rognierbenoit** [comment]
Unfortunately, I have to say the agenda is a bit tight, hence I suggest you go with Ligo for now. However we would be happy to stay in touch.
